### ISSUE TITLE
Failed to run "single_video_inference.py"

### ISSUE THREAD

**Issue by allenpubgit** [whwu95/FreeVA#1]
Thanks for your interesting work~

I try to run single_video_inference.py but the program returns nothing. Besides, I noticed the  D2 aggregation codes in "def temporal_aggregation()" have been canceled. So could you give some guidance to run your program?  Thanks.

**Comment by whwu95** [comment]
Thank you for your interest in my work! 

The code defaults to using simplest D1. Please change the ["num_frames"](https://github.com/whwu95/FreeVA/blob/d00b0511210d5f4c6642ab000f9a379f73a399f4/scripts/infer_video/run_one_video.sh#L2) from 8 to 4. 
If you need to use D2 aggregation, comment D1 and uncomment D2. Then, the "num_frames" can be increased to 8.
